"""aniversario-data

Revision ID: df30d903e656
Revises: 041e6c733717
Create Date: 2025-07-24 11:30:08.988028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df30d903e656'
down_revision = '041e6c733717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aniversario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(timezone=32), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aniversario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
